### ISSUE TITLE
Hash links don't work

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint.io#25]
If I go to a documentation page and click on the `#` to the right of a header, it usually (not always) sends to the top of the page. It shouldn't do that.

**Comment by MoOx** [comment]
It's a know bug https://github.com/MoOx/phenomic/issues/665.

**Comment by jeddy3** [comment]
I'm halfway through a local branch that updates phenomic to `@0.18` (and converts everything to stateless components) so that once a fix for this bug lands in phenomic we should be able to make use of it quickly.

**Comment by MoOx** [comment]
I pushed a fix into phenomic master if you want to try it. Will cut a release tomorrow, I tested it enough I think (even covered by tests)

**Comment by jeddy3** [comment]
@MoOx Thank you! I tried `0.19.4` this morning on my WIP branch. This issue i.e. 

> If I go to a documentation page and click on the # to the right of a header, it usually (not always) sends to the top of the page. It shouldn't do that.

Is now fixed! :) However the, I think, related issue of not moving down to an anchor _on a new page_ load is still present e.g. clicking http://stylelint.io/user-guide/faq/#how-do-i-lint-from-the-command-line won't load the page _and take you down to the correct FAQ entry_. Any ideas?

**Comment by MoOx** [comment]
I have also detected more scenarios that create bugs (eg: a page have a link to another page+hash trigger a full page load). Will fix all of that but will take a day or something :)

**Comment by MoOx** [comment]
0.19.5 should handle the bug you faced and more you didn't notice yet :)

**Comment by jeddy3** [comment]
@MoOx A big big thank you! `0.19.5` works great.  It was a prerequisite for integrating DocSearch (which would often return results to anchored headings). Things are looking promising for a new release of stylelint.io really soon. The last thing on my list is writing a couple of remark plugins (bundled as a phenomic loader plugin) to handle the extra markdown processing that the site needs.
